name       : libnm-legacy
version    : 1.16.4
release    : 4
source     :
    - https://download.gnome.org/sources/NetworkManager/1.16/NetworkManager-1.16.4.tar.xz : 130272a279aa26e197e544a270a832ee97ae6833504ff3a41c8ef9eeaed0d1f0
license    : GPL-2.0-or-later
component  : binary.compat
summary    : Legacy NetworkManager GLib functionality for Steam. DO NOT USE FOR ANYTHING ELSE.
description: |
    Legacy NetworkManager GLib functionality for Steam. DO NOT USE FOR ANYTHING ELSE.
emul32     : yes
devel      : no
libsplit   : no
builddeps  :
    - pkgconfig32(dbus-glib-1)
    - pkgconfig32(gio-2.0)
    - pkgconfig32(gudev-1.0)
    - pkgconfig32(libcurl)
    - pkgconfig32(liblzma)
    - pkgconfig32(libndp)
    - pkgconfig32(libnl-3.0)
    - pkgconfig32(nss)
    - pkgconfig32(uuid)
    - pkgconfig(mm-glib)
    - dhclient
    - libgcrypt-32bit-devel
    - ncurses-32bit-devel
    - readline-32bit-devel
rundeps    :
    - dhclient
setup      : |
    unset LD_AS_NEEDED
    %configure \
        --enable-polkit=disabled \
        --enable-modify-system \
        --disable-gtk-doc \
        --disable-introspection \
        --disable-ovs \
        --disable-polkit \
        --disable-polkit-agent \
        --disable-ppp \
        --disable-tests \
        --disable-wifi \
        --prefix=/usr \
        --with-dhclient=/usr/bin/dhclient \
        --with-dist-version="${version}-solus" \
        --with-libnm-glib \
        --with-nmcli=no \
        --with-nmtui=no \
        --with-udev-dir=/usr/lib/udev \
        --without-modem-manager-1 \
        --without-systemd-journal \
        --without-systemdsystemunitdir \
        --without-udev-dir
build      : |
    unset LD_AS_NEEDED
    %make
install    : |
    unset LD_AS_NEEDED
    %make_install
    # Mass cleanup
    rm -rf $installdir/{etc,var}
    rm -rf $installdir/usr/{bin,include,lib,sbin,share}
    rm -rf $installdir/%libdir%/pkgconfig
    # Specific libs
    rm $installdir/%libdir%/libnm.so*
